version: "3.7"
services:
  app-server:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - ride-service
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/driver?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  mysql:
    image: mysql:8
    networks:
      - ride-service
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=driver
    ports:
      - '3306:3306'

networks:
  ride-service: